permalink: /:year/:month/:day/:title/

# Site Info
title: Water Model's Page
tagline: "Later is Never"
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://w2nb.com
logo: "/public/logo.png"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Site configurationse
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: "/page:num"

version: 1.0.0

# About/contact
author:
  name: Zhu Fang
  description: A Stupid Boy
  contact:
    linkedin:  https://www.linkedin.com/in/fang-zhu-1764ba194/
    github:    https://github.com/zhufang9819
#    facebook:  <hide>
#    twitter:   https://twitter.com/Li_Zhihao
#    
#    email:      zhufang147@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - "/"
  Blog:
    - "/blog/"
    - { Categories: "/blog/categories/" }
    - { Tags: "/blog/tags/" }
  About:
    - "/about/"
  Github Project:
    - "https://github.com/zhufang9819/zhufang9819.github.io"

# Where are tags and categories displayed
tag_page: "/blog/tags/"
category_page: "/blog/categories/"

hero:
  image: /public/img/pirlo.jpg
  caption: Italian Midfield Master &copy; <a href="https://en.wikipedia.org/wiki/Andrea_Pirlo">Andrea Pirlo</a>

gems:
  - jekyll-paginate

# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: "UA-100604-12" # leave blank if you don't want google analytics
#disqus_short_name: '' # leave blank if you don't want disqus
